import type { Metadata } from 'next';
import Link from 'next/link';
import { Compass, ArrowUpRight } from 'lucide-react';
import { currentUser } from '@/lib/auth';
import { CompareProvider } from '@/components/compare';
import { PreferencesProvider, ThemeSwitch, CookieSettingsButton } from '@/components/preferences';
import { themeBootstrap } from '@/lib/preferences';
import './globals.css';

export const metadata:Metadata={title:{default:'EduClar · Următorul pas, mai clar',template:'%s · EduClar'},description:'Descoperă școli, înțelege rezultatele și găsește profesorul potrivit. Date oficiale cu surse citate și exemple demo etichetate.'};
export const dynamic='force-dynamic';
export default async function RootLayout({children}:{children:React.ReactNode}) {
  const user=await currentUser();
  return <html lang="ro" data-scroll-behavior="smooth" suppressHydrationWarning><head><script dangerouslySetInnerHTML={{__html:themeBootstrap}}/></head><body><PreferencesProvider><CompareProvider><a className="skip-link" href="#main">Sari la conținut</a><div className="demo-bar"><span className="status-dot"/>MVP local · date oficiale și exemple demo <Link href="/date">Despre date <ArrowUpRight size={11}/></Link></div><header className="header"><div className="container header-inner"><Link className="brand" href="/" aria-label="EduClar, pagina principală"><span className="brand-icon"><Compass size={25}/></span>edu<span>clar</span><span className="beta">BETA</span></Link><nav aria-label="Navigare principală"><Link href="/scoli">Școli</Link><Link href="/profesori">Profesori</Link><Link href="/meditatii">Meditații</Link><Link href="/absolventi">Absolvenți</Link></nav><div className="header-actions"><ThemeSwitch/><Link className="button small-button" href={user?'/cont':'/autentificare'}>{user?'Contul meu':'Intră în cont'}<ArrowUpRight size={15}/></Link></div></div></header><main id="main">{children}</main><footer className="footer"><div className="container"><div className="footer-top"><div><Link className="brand" href="/"><Compass size={25}/> educlar</Link><p>Mai multă claritate.<br/>Mai multă încredere în următorul pas.</p></div><div><h4>Explorează</h4><Link href="/scoli">Școli și licee</Link><Link href="/profesori">Profesori</Link><Link href="/meditatii">Meditații</Link><Link href="/date">Date oficiale și acoperire</Link></div><div><h4>Încredere și transparență</h4><Link href="/metodologie">Surse și metodologie</Link><Link href="/termeni">Termeni și condiții</Link><Link href="/confidentialitate">Confidențialitate · GDPR</Link><Link href="/cookies">Politica de cookies</Link><CookieSettingsButton/><Link href="/solicitari">Date personale și sesizări</Link></div><div className="footer-note"><span className="status-dot"/> Construit pentru comunitate<p>Elevi, părinți, profesori.<br/>O perspectivă mai completă asupra educației.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} EduClar · Proiect în dezvoltare</span><span>Datele spun o parte din poveste. Oamenii o completează.</span></div></div></footer></CompareProvider></PreferencesProvider></body></html>;
}
