import Link from 'next/link';
import { redirect } from 'next/navigation';
import { currentUser } from '@/lib/auth';
import { adminData, dashboard } from '@/lib/read';
import { PageHeading, Section, Form, Field, Submit, Notice, Badge, Empty } from '@/components/ui';
import { label } from '@/lib/labels';
export const metadata = { title: 'Administrare' };
export default async function Admin({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const user = await currentUser(); if (!user) redirect('/autentificare');
  const account = await dashboard(user.id);
  if (!account.profile?.staff_role || account.profile.disabled) return <div className="container page-content"><PageHeading title="Acces restricționat." description="Această pagină necesită un rol de moderator sau administrator."/><Link className="button" href="/cont">Înapoi în cont</Link></div>;
  const data = await adminData(user.id), p = await searchParams;
  return <div className="container page-content"><PageHeading title="Administrare" description={data.profile.staff_role === 'admin' ? 'Verificări, moderare, cereri privind datele și importuri.' : 'Moderarea recenziilor și raportărilor.'}/><Notice params={p}/><nav className="legal-nav"><a href="#moderare">Moderare</a><a href="#raportari">Raportări</a>{data.profile.staff_role === 'admin' && <><a href="#verificari">Verificări</a><a href="#date">Date personale</a><a href="#importuri">Surse și importuri</a></>}</nav>
    <Section id="moderare" title="Recenzii și răspunsuri în analiză">{data.reviews.map(r => <article className="review" key={r.id}><h3>{r.name}</h3><p className="preserve-lines">{r.body}</p>{r.status === 'pending' && <Moderate op="reviewDecide" id={r.id}/>} {r.status==='approved'&&r.reply_pending&&r.reply_pending_version===r.version && <><blockquote>{r.reply_pending}</blockquote><Moderate op="replyDecide" id={r.id} reviewVersion={r.version} replyToken={r.reply_pending_id}/></>}</article>)}{!data.reviews.length && <Empty title="Nu există recenzii în așteptare."/>}</Section>
    <Section id="raportari" title="Raportări">{data.reports.map(r => <article className="review" key={r.id}><h3>{r.name}</h3><p>{r.body}</p><p>Raportare: {r.reason}</p><Form op="reportResolve" returnTo="/admin"><input type="hidden" name="id" value={r.id}/><Field label="Motivul soluționării"><textarea name="reason" minLength={5} maxLength={1000} required/></Field><Submit>Închide raportarea</Submit></Form><p className="small">Dacă se impune retragerea recenziei, folosește formularul de mai jos.</p><Moderate op="reviewDecide" id={r.review_id}/></article>)}{!data.reports.length && <Empty title="Nu există raportări în așteptare."/>}</Section>
    {data.profile.staff_role === 'admin' && <><Section id="verificari" title="Verificări manuale">{data.checks?.map(c => <article className="review" key={c.id}><h3>{label(c.kind)} · {c.user_name}</h3><p>{c.teacher_name || c.school_id || c.family_id} · {c.academic_year} · {c.context}</p>{Object.keys(c.details || {}).length > 0 && <pre>{JSON.stringify(c.details, null, 2)}</pre>}{c.document_id ? <Link className="text-link" href={`/api/documente/${c.document_id}`}>Descarcă dovada privată</Link> : <p className="small">Fără document disponibil.</p>}<Moderate op="checkDecide" id={c.id}/></article>)}{!data.checks?.length && <Empty title="Nu există verificări în așteptare."/>}</Section>
    <Section id="date" title="Solicitări privind datele și sesizări"><Link className="button secondary" href="/admin/privacy">Execută solicitările și verifică retenția</Link>{data.privacy?.map(r => <article className="review" key={r.id}><h3>{label(r.kind)}</h3><p>Contact de test: {r.contact}</p><p className="preserve-lines">{r.message}</p>{r.teacher_id && <p>Profil: {r.teacher_id}</p>}<p className="small">Finalizează cererea prin generarea exportului, rectificarea datelor, retragerea conținutului sau ștergerea verificată.</p><Link className="text-link" href="/admin/privacy">Procesează solicitarea</Link></article>)}{!data.privacy?.length && <Empty title="Nu există solicitări în așteptare."/>}</Section>
    <Section id="importuri" title="Registrul surselor"><Form op="source" returnTo="/admin"><div className="field-grid"><Field label="Titlu"><input name="title" minLength={3} maxLength={200} required/></Field><Field label="URL HTTPS"><input name="url" type="url" pattern="https://.*" required/></Field><Field label="Editor"><input name="publisher" minLength={2} maxLength={200} required/></Field><Field label="An"><input name="year" type="number" min={2000} max={new Date().getFullYear()} defaultValue={2025} required/></Field></div><Field label="Licență / condiții de reutilizare"><textarea name="license" minLength={5} maxLength={2000} required/></Field><Submit>Înregistrează sursa</Submit></Form>{data.sources?.map(s => <article className="review" key={s.id}><h3>{s.title}</h3><p>{s.publisher} · {s.year} · {s.license}</p><Badge tone="gray">{label(s.status)}</Badge>{!s.demo && <Moderate op="sourceDecide" id={s.id}/>}</article>)}</Section>
    <Section title="Importuri: previzualizare și publicare"><p className="small">Loturile JSON sunt validate înainte de publicare. Un lot invalid nu modifică datele publice; reimportarea aceluiași lot nu dublează datele.</p><Form op="import" returnTo="/admin"><Field label="Tip"><select name="kind"><option value="schools">Instituții</option><option value="teachers">Profesori</option><option value="statistics">Statistici</option></select></Field><Field label="Sursă"><select name="source_id" required>{data.sources?.map(s => <option key={s.id} value={s.id}>{s.title} · {label(s.status)}</option>)}</select></Field><Field label="Fișier JSON"><input name="file" type="file" accept="application/json,.json" required/></Field><Submit>Validează și previzualizează</Submit></Form>{data.imports?.map(b => <article className="review" key={b.id}><h3>{b.kind} · {b.row_count} rânduri</h3><Badge tone="gray">{label(b.status)}</Badge>{b.errors?.length > 0 && <ul>{b.errors.map((e: string, i: number) => <li key={i}>{e}</li>)}</ul>}<details><summary>Primul rând validat</summary><pre>{JSON.stringify(b.sample, null, 2)}</pre></details>{b.status === 'pending' && <Form op="importPublish" returnTo="/admin"><input type="hidden" name="id" value={b.id}/><Field label="Motivul validării"><textarea name="reason" minLength={10} maxLength={2000} required/></Field><Submit>Publică lotul validat</Submit></Form>}</article>)}</Section>
    <Section title="Istoricul deciziilor">{data.audit?.map((a, i) => <div className="list-row" key={i}><div><strong>{a.action}</strong><p>{a.reason}</p><small>{new Date(a.created_at).toLocaleString('ro-RO', { timeZone: 'Europe/Bucharest' })}</small></div></div>)}</Section></>}
  </div>;
}
function Moderate({ op, id, reviewVersion,replyToken }: { op: string; id: string; reviewVersion?:number;replyToken?:string }) {
  return <Form op={op} returnTo="/admin"><input type="hidden" name="id" value={id}/>{op==='replyDecide'&&<><input type="hidden" name="review_version" value={reviewVersion}/><input type="hidden" name="reply_token" value={replyToken}/></>}<Field label="Motivul deciziei"><textarea name="reason" minLength={op === 'sourceDecide' ? 10 : 5} maxLength={2000} required/></Field><div className="tags"><button className="button" name="decision" value="approve">Aprobă</button><button className="button secondary" name="decision" value="reject">Respinge</button></div></Form>;
}
