import Link from 'next/link';
import type { Row } from '@/lib/db';
import type { schoolOptions } from '@/lib/read';
import { accountCenters, accountHref, type AccountRole, type AccountSection } from '@/lib/account-center';
import { Section, Form, Field, Submit, Badge, Empty } from '@/components/ui';
import { SchoolSelect } from '@/components/school-select';
import { label } from '@/lib/labels';

type AccountData = { profile: Row; families?: Row[]; reviews?: Row[]; requests?: Row[]; checks?: Row[]; teacher?: Row; alumni?: Row; privacy?: Row[]; ownOffers?: Row[] };
export function PersonalAccountSection({ role, section, data, userId, schools, staff, params: p, returnTo }: { role: AccountRole; section: AccountSection; data: AccountData; userId: string; schools: Awaited<ReturnType<typeof schoolOptions>>; staff: Row[]; params: Record<string, string | undefined>; returnTo: string }) {
  const profile = data.profile, user = { id: userId };
  const families = data.families || [], reviews = data.reviews || [], requests = data.requests || [], checks = data.checks || [];
  const ownTeacher = data.teacher;
  return <>
    {section === 'profil' && <Section id="profil" title="Profilul meu profesional" description="Datele profesionale sunt publice; telefonul contului rămâne privat.">{ownTeacher ? <>
      <div className="account-professional"><div className="avatar large">{ownTeacher.name.split(' ').map((name: string) => name[0]).slice(0, 2).join('')}</div><div><Badge>Profil revendicat</Badge><h3>{ownTeacher.name}</h3><p>{ownTeacher.subjects.join(' · ')}</p></div></div>
      <p className="preserve-lines">{ownTeacher.bio}</p>
      <div className="account-details"><div><span>Activitate profesională</span><strong>{ownTeacher.start_year ? `Din ${ownTeacher.start_year}` : 'În curs de confirmare'}</strong></div><div><span>Oferte active</span><strong>{data.ownOffers?.filter(offer => offer.active).length || 0}</strong></div></div>
      <div className="tags"><Link className="button" href={`/profesori/${ownTeacher.id}`}>Vezi profilul public</Link><Link className="button secondary" href={accountHref(role, 'verificari')}>Solicită corectarea datelor</Link></div>
      <p className="small">Răspunde recenziilor din pagina profilului public. Răspunsurile sunt moderate înainte de publicare.</p>
    </> : <Empty title="Revendică profilul tău profesional.">Asociază contul cu profilul de profesor pentru a publica oferte și a primi cereri de meditații.<br/><Link className="text-link" href={accountHref(role, 'verificari')}>Începe revendicarea</Link></Empty>}</Section>}
    {section === 'cereri' && (<Section id="cereri" title="Cereri de meditații" description="Contactele apar după acceptare. Pentru copiii sub 16 ani, este necesară autorizarea tutorelui.">{requests.map(r => <article key={r.id} className="list-row"><div><h3>{r.teacher_name} · {r.subject}</h3><p className="preserve-lines">{r.message}</p><Badge tone="gray">{label(r.status)}</Badge>{r.contact && <p>Contact: <a className="text-link" href={`tel:${r.contact}`}>{r.contact}</a></p>}{r.is_teacher && r.status === 'pending' && <Decision returnTo={returnTo} op="requestDecide" id={r.id}/>} {!r.is_teacher && r.status === 'guardian_pending' && families.some(f => f.id === r.family_id && f.parent_id === user.id) && <Decision returnTo={returnTo} op="guardianDecide" id={r.id} kind="request"/>}</div></article>)}{!requests.length && <Empty title="Nu ai cereri încă."><Link href={profile.role === 'teacher' ? accountHref(role, 'oferte') : '/meditatii'} className="text-link">{profile.role === 'teacher' ? 'Gestionează ofertele tale' : 'Explorează meditațiile'}</Link></Empty>}</Section>)}
    {section === 'recenzii' && (<Section id="recenzii" title={profile.role === 'parent' ? 'Recenziile familiei' : 'Recenziile mele'}>{reviews.map(r => <article className="review" key={r.id}><Link className="text-link" href={`/profesori/${r.teacher_id}`}>{r.name}</Link><p className="preserve-lines">{r.body}</p><Badge tone="gray">{label(r.status)}</Badge>{r.reason && <p className="small">Motiv: {r.reason}</p>}{r.own ? <Link className="text-link" href={`/profesori/${r.teacher_id}#main`}>Editează printr-o nouă trimitere pentru același context și an</Link> : r.status === 'guardian_pending' && <Decision returnTo={returnTo} op="guardianDecide" id={r.id} kind="review"/>}</article>)}{!reviews.length && <Empty title="Nu ai trimis recenzii."><Link href="/profesori" className="text-link">Găsește un profesor și descrie experiența ta</Link></Empty>}</Section>)}
    {section === 'familie' && (<Section id="familie" title={profile.role === 'parent' ? 'Copiii și autorizările' : 'Tutorele meu'} description="Verificarea legăturii este distinctă de confirmarea telefonului.">{families.map(f => <div className="list-row" key={f.id}><div><h3>{f.label}</h3><Badge tone="gray">{label(f.status)}</Badge>{f.status === 'invited' && f.invited_phone === profile.phone_number && profile.role === 'parent' && <Form returnTo={returnTo} op="familyAccept"><input type="hidden" name="id" value={f.id}/><Submit>Acceptă invitația și solicită verificarea</Submit></Form>}{f.parent_id === user.id && f.parent_consented && <Form returnTo={returnTo} op="familyRevoke"><input type="hidden" name="id" value={f.id}/><Submit secondary>Retrage autorizarea</Submit></Form>}</div></div>)}{['parent', 'student'].includes(profile.role) && <details open={!families.length}><summary>{profile.role === 'parent' ? 'Adaugă un copil în cont' : 'Invită un tutore'}</summary><Form returnTo={returnTo} op="family"><Field label="Nume de test / etichetă copil"><input name="label" minLength={2} maxLength={80} required/></Field><Field label="Instituția copilului"><SchoolSelect schools={schools}/></Field>{profile.role === 'student' && <Field label="Telefonul tutorelui"><input name="parent_phone" type="tel" pattern="\+[1-9][0-9]{7,14}" placeholder="+40700000002" required/></Field>}<Submit>Înregistrează legătura</Submit></Form></details>}</Section>)}
    {section === 'verificari' && (<Section id="verificari" title="Verificări și revendicări" description="Încarcă exclusiv documente sintetice de test, PDF, PNG sau JPEG, maximum 5 MB. Într-un serviciu real trebuie mascate CNP-ul, adresa și datele nerelevante.">{checks.map(c => <div className="list-row" key={c.id}><div><strong>{label(c.kind)} · {c.teacher_name || c.school_name || 'Legătură de tutelă'}</strong><p>{c.academic_year} · {label(c.status)}</p>{c.reason && <p className="small">{c.reason}</p>}</div></div>)}
      <Form returnTo={returnTo} op="check"><div className="field-grid"><Field label="Ce verificăm?"><select name="kind" defaultValue={profile.role === 'teacher' ? (ownTeacher && !p.teacher ? 'correction' : 'claim') : 'school'}><option value="school">Apartenență școlară</option><option value="relationship">Relație cu profesorul</option>{profile.role === 'teacher' && <><option value="claim">Revendicare profil profesor</option><option value="correction">Corectare date profesionale</option></>}{profile.role === 'parent' && <option value="guardian">Tutelă</option>}</select></Field><Field label="An școlar"><input name="academic_year" defaultValue="2025–2026" pattern="20[0-9]{2}[–-]20[0-9]{2}" required/></Field></div><Field label="Instituție"><SchoolSelect schools={schools} required={false}/></Field><Field label="Profesor (pentru relație, revendicare sau corectare)"><select name="teacher_id" defaultValue={p.teacher || ownTeacher?.id || ''}><option value="">Alege profesorul</option>{staff.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Context"><select name="context"><option value="class">La clasă</option><option value="tutoring">La meditații</option></select></Field>{families.length > 0 && <Field label="Legătura de tutelă (pentru copil sau părinte)"><select name="family_id"><option value="">Nu se aplică</option>{families.map(f => <option key={f.id} value={f.id}>{f.label} · {label(f.status)}</option>)}</select></Field>} {ownTeacher && <details><summary>Date profesionale propuse (completează pentru o cerere de corectare)</summary><div className="field-grid"><Field label="Nume propus"><input name="correction_name" defaultValue={ownTeacher.name} minLength={3} maxLength={120}/></Field><Field label="Materie propusă"><input name="correction_subject" defaultValue={ownTeacher.subjects[0]} minLength={2} maxLength={80}/></Field><Field label="Instituție propusă"><SchoolSelect schools={schools} name="correction_school_id" required={false}/></Field><Field label="Anul începerii activității"><input name="correction_start_year" type="number" min={1950} max={new Date().getFullYear()} defaultValue={ownTeacher.start_year || ''}/></Field></div></details>}<Field label="Dovadă de test"><input type="file" name="document" accept="application/pdf,image/png,image/jpeg" required/></Field><Submit>Trimite pentru verificare</Submit></Form>
    </Section>)}
    {section === 'oferte' && (<Section id="oferte" title="Ofertele mele">{ownTeacher ? <><Link className="text-link" href={`/profesori/${ownTeacher.id}`}>{ownTeacher.name}</Link>{data.ownOffers?.map(o => <div className="list-row" key={o.id}><div><strong>{o.subject} · {o.level}</strong><p>{o.price} lei · {o.active ? 'Activă' : 'Inactivă'}</p>{o.active && <Form returnTo={returnTo} op="offerDisable"><input type="hidden" name="id" value={o.id}/><Submit secondary>Dezactivează oferta</Submit></Form>}</div></div>)}<Form returnTo={returnTo} op="offer"><Field label="Materie"><select name="subject">{ownTeacher.subjects.map((s: string) => <option key={s}>{s}</option>)}</select></Field><Field label="Nivel"><input name="level" defaultValue="BAC și admitere" minLength={2} maxLength={120} required/></Field><div className="field-grid"><Field label="Format"><select name="format"><option value="online">Online</option><option value="fizic">Fizic</option><option value="mixt">Mixt</option></select></Field><Field label="Localitate"><input name="city" minLength={2} maxLength={100} required defaultValue="București"/></Field><Field label="Durată (minute)"><input type="number" name="duration" min={30} max={240} defaultValue={90} required/></Field><Field label="Preț (lei)"><input type="number" name="price" min={0} max={10000} defaultValue={150} required/></Field></div><Field label="Prezentare"><textarea name="bio" defaultValue={ownTeacher.bio} minLength={20} maxLength={2000} required/></Field><label className="check-field"><input type="checkbox" name="not_current_students" value="yes" required/>Nu ofer meditații contra cost elevilor cărora le predau la clasă.</label><Submit>Publică / actualizează oferta</Submit></Form></> : <p>Revendică profilul și obține verificarea înainte de a publica oferte.</p>}</Section>)}
    {section === 'absolvent' && (<Section id="absolvent" title="Profil de absolvent" description="Profil privat până când alegi publicarea. Datele despre carieră sunt autodeclarate."><Form returnTo={returnTo} op="alumni"><Field label="Nume public"><input name="public_name" defaultValue={data.alumni?.public_name || ''} minLength={2} maxLength={100} required/></Field><Field label="Liceu"><SchoolSelect schools={schools} defaultValue={data.alumni?.school_id}/></Field><Field label="Promoție"><input name="graduation" type="number" min={1950} max={new Date().getFullYear()} defaultValue={data.alumni?.graduation || 2021} required/></Field><Field label="Facultate / traseu după liceu"><input name="university" minLength={2} maxLength={150} defaultValue={data.alumni?.university || ''} required/></Field><Field label="Domeniu profesional"><input name="field" minLength={2} maxLength={100} defaultValue={data.alumni?.field || ''} required/></Field><Field label="Povestea ta"><textarea name="bio" minLength={20} maxLength={1500} defaultValue={data.alumni?.bio || ''} required/></Field><label className="check-field"><input type="checkbox" name="published" value="yes" defaultChecked={data.alumni?.published || false}/>Publică profilul. Debifează și salvează pentru retragere.</label><Submit>Salvează profilul</Submit></Form></Section>)}
    {section === 'setari' && (<Section id="setari" title="Cont și confidențialitate"><div className="account-details"><div><span>Tipul contului</span><strong>{accountCenters[role].name}</strong></div><div><span>Pseudonim public</span><strong>{profile.pseudonym}</strong></div><div><span>Telefon privat</span><strong>{profile.phone_number}</strong></div></div>{data.privacy?.map(r => <div className="list-row" key={r.id}><div><strong>{label(r.kind)}</strong><p>{label(r.status)}{r.reason ? ` · ${r.reason}` : ''}</p></div></div>)}<Link className="button secondary" href="/solicitari">Trimite o solicitare</Link><p className="small">Ștergerea contului și retragerea unui profil de profesor sunt cereri distincte.</p>{role !== 'admin' && role !== 'moderator' && profile.age_band === 'adult' && profile.role !== 'alumni' && <div className="account-secondary-action"><strong>Ai o poveste de absolvent?</strong><p>Poți publica traseul tău după liceu și din acest cont.</p><Link className="text-link" href={accountHref(role, 'absolvent')}>Gestionează povestea de absolvent</Link></div>}{role === 'teacher' && <div className="account-secondary-action"><strong>Contribuțiile tale personale</strong><p>Urmărește experiențele pe care le-ai împărtășit comunității.</p><Link className="text-link" href={accountHref(role, 'recenzii')}>Vezi recenziile mele</Link></div>}</Section>)}
  </>;
}

function Decision({ op, id, kind, returnTo }: { op: string; id: string; kind?: string; returnTo: string }) {
  return <Form op={op} returnTo={returnTo}><input type="hidden" name="id" value={id}/>{kind && <input type="hidden" name="kind" value={kind}/>}<div className="tags"><button className="button small-button" name="decision" value="approve">Acceptă</button><button className="button secondary small-button" name="decision" value="reject">Refuză</button></div></Form>;
}
