'use client';
import { useState } from 'react';
import Link from 'next/link';
export function SchoolFilters({ params, places, years }: { params: Record<string,string|undefined>; places: { county: string; city: string }[]; years: number[] }) {
  const [county, setCounty] = useState(params.county || ''), [city, setCity] = useState(params.city || '');
  const counties = [...new Set(places.map(p => p.county))];
  const cities = [...new Set(places.filter(p => !county || p.county === county).map(p => p.city))];
  return <form action="/scoli" className="filters"><label className="search-field">Școală sau localitate<input aria-label="Școală sau localitate" name="q" defaultValue={params.q} placeholder="Caută un nume sau un oraș…"/></label><label>Județ<select aria-label="Județ" name="county" value={county} onChange={e => { setCounty(e.target.value); setCity(''); }}><option value="">Toate județele</option>{counties.map(c => <option key={c}>{c}</option>)}</select></label><label>Localitate<select aria-label="Localitate" name="city" value={city} onChange={e => setCity(e.target.value)}><option value="">Toate localitățile</option>{cities.map(c => <option key={c}>{c}</option>)}</select></label><label>Tip<select aria-label="Tip" name="type" defaultValue={params.type || ''}><option value="">Toate tipurile</option><option value="colegiu">Colegiu</option><option value="liceu">Liceu</option><option value="gimnaziu">Gimnaziu</option></select></label><label>Date<select aria-label="Date" name="data" defaultValue={params.data || ''}><option value="">Toate seturile</option><option value="official">Doar oficiale</option><option value="demo">Doar demonstrative</option></select></label><label>An rezultate<select aria-label="An rezultate" name="year" defaultValue={params.year || ''}><option value="">Cel mai recent disponibil</option>{years.map(y=><option key={y}>{y}</option>)}</select></label><label>Examen<select aria-label="Examen" name="exam" defaultValue={params.exam || ''}><option value="">Potrivit tipului de școală</option><option>BAC</option><option>EN</option><option value="ADMITERE">Admitere</option></select></label><button className="button">Caută</button><Link className="text-link" href="/scoli">Resetează</Link></form>;
}
