import Link from 'next/link';
import type { adminData } from '@/lib/read';
import type { AccountSection } from '@/lib/account-center';
import { Section, Form, Field, Submit, Badge, Empty } from '@/components/ui';
import { label } from '@/lib/labels';

type StaffData = Awaited<ReturnType<typeof adminData>>;
export function StaffAccountSection({ section, data, returnTo }: { section: AccountSection; data: StaffData; returnTo: string }) {
  return <>
    {section === 'moderare' && (<Section id="moderare" title="Recenzii și răspunsuri în analiză">{data.reviews.map(r => <article className="review" key={r.id}><h3>{r.name}</h3><p className="preserve-lines">{r.body}</p>{r.status === 'pending' && <Moderate returnTo={returnTo} op="reviewDecide" id={r.id}/>} {r.reply_pending && <><blockquote>{r.reply_pending}</blockquote><Moderate returnTo={returnTo} op="replyDecide" id={r.id}/></>}</article>)}{!data.reviews.length && <Empty title="Nu există recenzii în așteptare."/>}</Section>)}
    {section === 'raportari' && (<Section id="raportari" title="Raportări">{data.reports.map(r => <article className="review" key={r.id}><h3>{r.name}</h3><p>{r.body}</p><p>Raportare: {r.reason}</p><Form op="reportResolve" returnTo={returnTo}><input type="hidden" name="id" value={r.id}/><Field label="Motivul soluționării"><textarea name="reason" minLength={5} maxLength={1000} required/></Field><Submit>Închide raportarea</Submit></Form><p className="small">Dacă se impune retragerea recenziei, folosește formularul de mai jos.</p><Moderate returnTo={returnTo} op="reviewDecide" id={r.review_id}/></article>)}{!data.reports.length && <Empty title="Nu există raportări în așteptare."/>}</Section>)}
    {section === 'verificari' && (<Section id="verificari" title="Verificări manuale">{data.checks?.map(c => <article className="review" key={c.id}><h3>{label(c.kind)} · {c.user_name}</h3><p>{c.teacher_name || c.school_id || c.family_id} · {c.academic_year} · {c.context}</p>{Object.keys(c.details || {}).length > 0 && <pre>{JSON.stringify(c.details, null, 2)}</pre>}{c.document_id ? <Link className="text-link" href={`/api/documente/${c.document_id}`}>Descarcă dovada privată</Link> : <p className="small">Fără document disponibil.</p>}<Moderate returnTo={returnTo} op="checkDecide" id={c.id}/></article>)}{!data.checks?.length && <Empty title="Nu există verificări în așteptare."/>}</Section>)}
    {section === 'date' && (<Section id="date" title="Solicitări privind datele și sesizări">{data.privacy?.map(r => <article className="review" key={r.id}><h3>{label(r.kind)}</h3><p>Contact de test: {r.contact}</p><p className="preserve-lines">{r.message}</p>{r.teacher_id && <p>Profil: {r.teacher_id}</p>}<p className="small">Pentru acces sau rectificare, efectuează analiza și pregătește răspunsul înainte de a închide cererea. Nu există trimitere automată de email.</p><Moderate returnTo={returnTo} op="privacyDecide" id={r.id} identity/></article>)}{!data.privacy?.length && <Empty title="Nu există solicitări în așteptare."/>}</Section>)}
    {section === 'surse' && (<Section id="surse" title="Registrul surselor"><Form op="source" returnTo={returnTo}><div className="field-grid"><Field label="Titlu"><input name="title" minLength={3} maxLength={200} required/></Field><Field label="URL HTTPS"><input name="url" type="url" pattern="https://.*" required/></Field><Field label="Editor"><input name="publisher" minLength={2} maxLength={200} required/></Field><Field label="An"><input name="year" type="number" min={2000} max={new Date().getFullYear()} defaultValue={2025} required/></Field></div><Field label="Licență / condiții de reutilizare"><textarea name="license" minLength={5} maxLength={2000} required/></Field><Submit>Înregistrează sursa</Submit></Form>{data.sources?.map(s => <article className="review" key={s.id}><h3>{s.title}</h3><p>{s.publisher} · {s.year} · {s.license}</p><Badge tone="gray">{label(s.status)}</Badge>{!s.demo && <Moderate returnTo={returnTo} op="sourceDecide" id={s.id}/>}</article>)}</Section>)}
    {section === 'importuri' && (<Section id="importuri" title="Importuri: previzualizare și publicare"><p className="small">Loturile JSON sunt validate înainte de publicare. Un lot invalid nu modifică datele publice; reimportarea aceluiași lot nu dublează datele.</p><Form op="import" returnTo={returnTo}><Field label="Tip"><select name="kind"><option value="schools">Instituții</option><option value="teachers">Profesori</option><option value="statistics">Statistici</option></select></Field><Field label="Sursă"><select name="source_id" required>{data.sources?.map(s => <option key={s.id} value={s.id}>{s.title} · {label(s.status)}</option>)}</select></Field><Field label="Fișier JSON"><input name="file" type="file" accept="application/json,.json" required/></Field><Submit>Validează și previzualizează</Submit></Form>{data.imports?.map(b => <article className="review" key={b.id}><h3>{b.kind} · {b.row_count} rânduri</h3><Badge tone="gray">{label(b.status)}</Badge>{b.errors?.length > 0 && <ul>{b.errors.map((e: string, i: number) => <li key={i}>{e}</li>)}</ul>}<details><summary>Primul rând validat</summary><pre>{JSON.stringify(b.sample, null, 2)}</pre></details>{b.status === 'pending' && <Form op="importPublish" returnTo={returnTo}><input type="hidden" name="id" value={b.id}/><Field label="Motivul validării"><textarea name="reason" minLength={10} maxLength={2000} required/></Field><Submit>Publică lotul validat</Submit></Form>}</article>)}</Section>)}
    {section === 'istoric' && (<Section id="istoric" title="Istoricul deciziilor">{data.audit?.map((a, i) => <div className="list-row" key={i}><div><strong>{a.action}</strong><p>{a.reason}</p><small>{new Date(a.created_at).toLocaleString('ro-RO', { timeZone: 'Europe/Bucharest' })}</small></div></div>)}</Section>)}
  </>;
}
function Moderate({ op, id, identity = false, returnTo }: { op: string; id: string; identity?: boolean; returnTo: string }) {
  return <Form op={op} returnTo={returnTo}><input type="hidden" name="id" value={id}/><Field label="Motivul deciziei"><textarea name="reason" minLength={op === 'privacyDecide' || op === 'sourceDecide' ? 10 : 5} maxLength={2000} required/></Field>{identity && <label className="check-field"><input type="checkbox" name="identity_confirmed" value="yes" required/>Am verificat solicitantul și am efectuat analiza necesară.</label>}<div className="tags"><button className="button" name="decision" value="approve">Aprobă</button><button className="button secondary" name="decision" value="reject">Respinge</button></div></Form>;
}
