import Link from 'next/link';
import { ArrowUpRight, MapPin, School, ShieldCheck, BookOpen, ArrowRight } from 'lucide-react';
import type { ReactNode } from 'react';
import type { Row } from '@/lib/db';
import { act } from '@/app/actions';
import { CompareToggle } from './compare';

export const formatNumber=(n:unknown)=>n===null||n===undefined?'—':Number(n).toLocaleString('ro-RO',{maximumFractionDigits:2,minimumFractionDigits:Number(n)%1?2:0});
export function Badge({children,tone='green'}:{children:ReactNode;tone?:string}) {return <span className={`badge ${tone}`}>{children}</span>;}
export function PageHeading({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}) {return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{children}</div>;}
export function Empty({title='Încă nu sunt informații aici.',children}:{title?:string;children?:ReactNode}) {return <div className="empty"><BookOpen size={28}/><h3>{title}</h3><p>{children||'Revino după următoarea actualizare sau încearcă alte filtre.'}</p></div>;}
export function Notice({params}:{params:Record<string,string|undefined>}) {return <>{params.error&&<div role="alert" className="notice error">{params.error}</div>}{params.success&&<div role="status" className="notice success">{params.success}</div>}</>;}
export function Form({op,returnTo='/cont',children,className='',...props}:{op:string;returnTo?:string;children:ReactNode;className?:string;id?:string}) {return <form action={act} className={`form ${className}`} {...props}><input type="hidden" name="op" value={op}/><input type="hidden" name="returnTo" value={returnTo}/>{children}</form>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}) {return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Submit({children='Enregistrează',secondary=false}:{children?:ReactNode;secondary?:boolean}) {return <button className={`button ${secondary?'secondary':''}`} type="submit">{children}</button>;}
export function Section({title,description,children,id}:{title:string;description?:string;children:ReactNode;id?:string}) {return <section className="panel" id={id}><div className="section-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div></div>{children}</section>;}
export function SchoolCard({school:s,index=0}:{school:Row;index?:number}) {return <article className="school-card"><div className={`school-visual v${index%4}`}><School size={36} strokeWidth={1.3}/><span className="visual-lines"/><Badge tone="white">{s.type==='colegiu'?'Colegiu':s.type==='liceu'?'Liceu':'Gimnaziu'}</Badge></div><div className="school-card-content"><div className="meta"><MapPin size={13}/>{s.city}, {s.county}</div><Link href={`/scoli/${s.id}`} className="card-title">{s.name}<ArrowUpRight size={18}/></Link><div className="school-metrics"><div><span>{s.type==='gimnaziu'?'Medie EN':'Medie BAC'}</span><strong>{formatNumber(s.average)}</strong></div><div><span>Elevi înscriși</span><strong>{formatNumber(s.enrolled)}</strong></div></div><div className="card-bottom">{s.demo?<Badge tone="amber">Date demo</Badge>:<Badge>Date oficiale</Badge>}<CompareToggle school={{id:s.id,name:s.name}}/></div></div></article>;}
export function TeacherCard({teacher:t}:{teacher:Row}) {return <article className="teacher-card"><div className="avatar">{t.name.split(' ').map((x:string)=>x[0]).slice(0,2).join('')}</div><div><div className="meta">{t.subjects.join(' · ')}</div><Link className="card-title" href={`/profesori/${t.id}`}>{t.name}<ArrowUpRight size={17}/></Link><p className="small">{t.schools?.[0]?.name||'Instituție în curs de confirmare'}</p><div className="tags">{t.claimed&&<Badge><ShieldCheck size={12}/>Revendicat</Badge>}{t.demo&&<Badge tone="amber">Demo</Badge>}</div></div></article>;}
export function Source({title,url}:{title:string;url:string}) {return <a className="source" href={url} target={url.startsWith('https')?'_blank':undefined} rel="noreferrer">Sursa: {title}<ArrowUpRight size={12}/></a>;}
export function StepLink({href,number,title,description}:{href:string;number:string;title:string;description:string}) {return <Link className="step-link" href={href}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div><ArrowRight size={18}/></Link>;}
