import Link from 'next/link';
import { LegalPage } from '@/components/legal';
export const metadata = { title: 'Confidențialitate și GDPR' };
export default function Privacy() {
  return <LegalPage title="Confidențialitate și GDPR"><h2>Date folosite în prototip</h2><p>Stocăm telefonul de test, sesiunea, rolul și grupa de vârstă, pseudonimul, legăturile de tutelă, cererile de verificare, contribuțiile, cererile de meditații și solicitările privind datele. Sesiunile pot include IP și informații despre browser. Documentele de test sunt criptate în afara directorului public. Baza de date este persistentă pe calculatorul care rulează aplicația.</p>
    <h2>Scop și vizibilitate</h2><p>Folosim datele pentru autentificare, verificări, autorizarea minorilor, publicarea solicitată, moderare, cereri și prevenirea abuzului. Telefonul și identitatea privată a autorilor nu apar în recenzii. Documentele sunt accesibile numai administratorilor autorizați. Datele de contact pentru meditații sunt vizibile participanților după acceptare și când autorizarea tutorelui este activă. Profilul de absolvent rămâne privat până la alegerea explicită de publicare.</p>
    <h2>Informarea necesară înainte de lansare</h2><p>Pentru un serviciu real, operatorul trebuie să documenteze separat temeiurile pentru fiecare scop: executarea serviciului solicitat, obligațiile legale, interesele legitime justificate și consimțământul când este necesar. Acceptarea termenilor nu reprezintă un acord global pentru prelucrare. Trebuie completate identitatea operatorului, destinatarii, furnizorii, transferurile internaționale, retenția și evaluarea riscurilor privind minorii.</p>
    <h2>Cât timp păstrăm datele</h2><p>Documentele de verificare sunt eliminate la următoarea operație de curățare după decizie; cererile abandonate expiră după 30 de zile. Curățarea se execută la utilizarea contului, administrării și acțiunilor. Conturile și contribuțiile de test persistă până la retragere, soluționarea cererii sau resetarea mediului. Ștergerea contului elimină telefonul, profilul de absolvent și conținutul contribuțiilor; referințele tehnice și jurnalul minim al deciziilor rămân. Retenția completă, inclusiv pentru jurnale și copii de siguranță, trebuie stabilită pentru lansare.</p>
    <h2>Drepturi și solicitări</h2><p>Poți solicita acces, rectificare, ștergere, restricționare, opoziție ori portabilitate, când sunt aplicabile, și retrage consimțământul. Formularul este disponibil fără cont; ștergerea unui cont necesită asocierea și verificarea titularului. Verificarea identității trebuie să fie proporțională. În serviciul real, cererile se soluționează de regulă într-o lună, cu prelungiri motivate în cazurile prevăzute de lege. Poți depune plângere la <a href="https://www.dataprotection.ro/" target="_blank" rel="noreferrer">ANSPDCP</a>.</p><p>Prototipul înregistrează cererile local și permite analiza lor de către administrator; nu trimite emailuri și nu oferă încă un export automat. Nu luăm decizii juridice exclusiv automatizate. Publicarea, moderarea și revendicările presupun verificare umană.</p><Link className="button" href="/solicitari">Trimite o solicitare de test</Link>
    <h2>Conversațiile cu Jelly</h2><p>Asistentul trimite mesajul și cel mult patru perechi de mesaje anterioare furnizorului AI configurat de operator, prin FreeLLMAPI sau Gemini. Nu primește telefonul, documentele ori datele private ale contului. Conversația afișată rămâne în memoria paginii și dispare la reîncărcare. Nu trimite date personale sau informații confidențiale.</p><p>Pentru întrebări repetate, răspunsul este păstrat criptat în baza de date, separat pentru fiecare cont, implicit timp de 24 de ore. Mesajele nu sunt salvate în clar în cache. Un răspuns expirat nu mai este servit; curățarea se execută la următorul mesaj. Butonul de ștergere din Jelly elimină imediat răspunsurile salvate pentru cont. Contoarele tehnice pentru limite sunt păstrate cel mult 35 de zile și curățate la utilizare. Furnizorul AI poate avea propria politică de retenție.</p><h2>Cookies și surse</h2><p>Poți modifica preferințele din <Link href="/cookies">politica de cookies</Link>. Baza normativă pentru documentul ce va fi validat la lansare: <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" target="_blank" rel="noreferrer">Regulamentul (UE) 2016/679</a>. Implementarea tehnică a prototipului nu certifică conformitatea juridică a unui serviciu public.</p>
  </LegalPage>;
}
