import Link from 'next/link';
import { LegalPage } from '@/components/legal';
export const metadata = { title: 'Confidențialitate și GDPR' };
export default function Privacy() {
  return <LegalPage title="Confidențialitate și GDPR"><h2>Date folosite în prototip</h2><p>Stocăm telefonul de test, sesiunea, rolul și grupa de vârstă, pseudonimul, legăturile de tutelă, cererile de verificare, contribuțiile, cererile de meditații și solicitările privind datele. Sesiunile pot include IP și informații despre browser. Documentele de test sunt criptate în afara directorului public. Baza de date este persistentă pe calculatorul care rulează aplicația.</p>
    <h2>Scop și vizibilitate</h2><p>Folosim datele pentru autentificare, verificări, autorizarea minorilor, publicarea solicitată, moderare, cereri și prevenirea abuzului. Telefonul și identitatea privată a autorilor nu apar în recenzii. Documentele sunt accesibile numai administratorilor autorizați. Datele de contact pentru meditații sunt vizibile participanților după acceptare și când autorizarea tutorelui este activă. Profilul de absolvent rămâne privat până la alegerea explicită de publicare.</p>
    <h2>Informarea necesară înainte de lansare</h2><p>Pentru un serviciu real, operatorul trebuie să documenteze separat temeiurile pentru fiecare scop: executarea serviciului solicitat, obligațiile legale, interesele legitime justificate și consimțământul când este necesar. Acceptarea termenilor nu reprezintă un acord global pentru prelucrare. Trebuie completate identitatea operatorului, destinatarii, furnizorii, transferurile internaționale, retenția și evaluarea riscurilor privind minorii.</p>
    <h2>Cât timp păstrăm datele</h2><p>Documentele de verificare sunt eliminate la următoarea operație de curățare după decizie; cererile abandonate expiră după 30 de zile. Jobul de retenție rulează la pornirea serverului și apoi la fiecare oră, inclusiv fără vizite. Eșecurile de ștergere sunt înregistrate și reîncercate; fișierele în curs de ștergere sunt inaccesibile. Conturile și contribuțiile de test persistă până la retragere, soluționarea cererii sau resetarea mediului. Ștergerea contului elimină telefonul, profilul de absolvent și conținutul contribuțiilor; răspunsurile profesorului, motivele raportărilor și ale verificărilor sunt eliminate, iar dovezile sunt puse în coada de ștergere. Referințele tehnice minimizate rămân pentru integritatea relațiilor; textele cererilor finalizate și jurnalele deciziilor au retenție de 30 de zile în prototip. Retenția completă, inclusiv pentru jurnale și copii de siguranță, trebuie stabilită pentru lansare.</p>
    <h2>Drepturi și solicitări</h2><p>Poți solicita acces, rectificare, ștergere, restricționare, opoziție ori portabilitate, când sunt aplicabile, și retrage consimțământul. Formularul este disponibil fără cont; ștergerea unui cont necesită asocierea și verificarea titularului. Verificarea identității trebuie să fie proporțională. În serviciul real, cererile se soluționează de regulă într-o lună, cu prelungiri motivate în cazurile prevăzute de lege. Poți depune plângere la <a href="https://www.dataprotection.ro/" target="_blank" rel="noreferrer">ANSPDCP</a>.</p><p>Prototipul înregistrează cererile local și permite analiza lor de către administrator; nu trimite emailuri. După verificare, cererile de acces generează un export privat, disponibil titularului autentificat și administratorului timp de 7 zile. Rectificările și retragerile conținutului sunt aplicate și înregistrate înainte de finalizarea cererii. Nu luăm decizii juridice exclusiv automatizate. Publicarea, moderarea și revendicările presupun verificare umană.</p><Link className="button" href="/solicitari">Trimite o solicitare de test</Link>
    <h2>Cookies și surse</h2><p>Poți modifica preferințele din <Link href="/cookies">politica de cookies</Link>. Baza normativă pentru documentul ce va fi validat la lansare: <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" target="_blank" rel="noreferrer">Regulamentul (UE) 2016/679</a>. Implementarea tehnică a prototipului nu certifică conformitatea juridică a unui serviciu public.</p>
  </LegalPage>;
}
