import Link from 'next/link';
import { LegalPage } from '@/components/legal';
export const metadata = { title: 'Termeni și condiții' };
export default function Terms() {
  return <LegalPage title="Termeni și condiții"><h2>1. Serviciul și accesul</h2><p>EduClar este un prototip de informare despre educație: catalog, rezultate agregate, profiluri, recenzii și cereri de meditații. Toate persoanele și rezultatele marcate demo sunt fictive. În acest mediu nu se trimit SMS-uri reale și nu se procesează plăți. Folosește date și documente sintetice de test.</p>
    <h2>2. Conturi și minori</h2><p>Telefonul verifică accesul la număr, nu identitatea. Folosește un cont propriu și nu te prezenta drept altă persoană. Conturile de elevi sub 16 ani au nevoie de tutore verificat și autorizare pentru contribuții; retragerea autorizării blochează interacțiunile. Profilurile publice de absolvenți sunt disponibile adulților.</p>
    <h2>3. Conținut și moderare</h2><p>Publică numai experiențe autentice și conținut pe care ai dreptul să îl folosești. Sunt interzise amenințările, discriminarea, hărțuirea, publicarea datelor private ale altora și acuzațiile fără suport factual. Recenziile și răspunsurile profesorilor se moderează. Verificarea documentelor nu garantează adevărul fiecărei afirmații. O editare a recenziei reia moderarea.</p><p>Autorul păstrează drepturile asupra contribuției și permite afișarea ei în cadrul serviciului, în scopul publicării solicitate. Sesizările nu elimină automat conținutul; sunt analizate, iar deciziile se motivează. Poți cere reanalizarea prin <Link href="/solicitari">formularul de sesizări</Link>.</p>
    <h2>4. Meditații și relația dintre participanți</h2><p>Platforma facilitează cererea și răspunsul. Durata, locul, plata, anularea și desfășurarea ședințelor se stabilesc direct între participanți. EduClar nu este parte la contractul de meditații și nu garantează disponibilitatea profesorului, siguranța întâlnirilor sau rezultatele la examene. Verifică oferta și condițiile înainte de a accepta; pentru minori implică tutorele. Nu solicita meditații contra cost profesorului care îți predă la clasă.</p>
    <h2>5. Informații și limitele răspunderii</h2><p>Statisticile istorice și opiniile nu reprezintă recomandări individuale sau promisiuni de performanță. Sursele externe și conținutul utilizatorilor pot avea erori ori actualizări întârziate. Deciziile educaționale și interacțiunile dintre utilizatori le aparțin acestora. În limitele legii, operatorul nu răspunde pentru actele independente ale terților, pentru rezultatele școlare sau pentru prejudicii care nu îi sunt imputabile.</p><p>Această clauză nu exclude răspunderea pentru intenție, culpă gravă ori alte situații în care legea interzice excluderea. Nu limitează drepturile obligatorii privind protecția datelor, viața, sănătatea, integritatea sau protecția consumatorilor. <a href="https://legislatie.just.ro/Public/DetaliiDocumentAfis/304560" target="_blank" rel="noreferrer">Codul civil, art. 1355</a>.</p>
    <h2>6. Suspendare și modificări</h2><p>Contribuțiile care încalcă regulile pot fi respinse sau retrase, cu motiv și posibilitatea unei sesizări. Versiunea și data documentelor sunt afișate. Modificările materiale necesită o nouă informare și, dacă este necesar, un nou acord. Legea română se aplică în măsura permisă de normele imperative, fără restrângerea drepturilor legale ale utilizatorilor.</p>
  </LegalPage>;
}
