import Link from 'next/link';
import { redirect } from 'next/navigation';
import { currentUser } from '@/lib/auth';
import { dashboard, schoolOptions, teachers } from '@/lib/read';
import { PageHeading, Section, Form, Field, Submit, Badge, Notice, Empty } from '@/components/ui';
import { SchoolSelect } from '@/components/school-select';
import { Logout } from '@/components/login';
import { label } from '@/lib/labels';
import { legal } from '@/lib/legal';
export const metadata = { title: 'Contul meu' };
export default async function Account({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const user = await currentUser(); if (!user) redirect('/autentificare');
  const p = await searchParams, data = await dashboard(user.id), profile = data.profile;
  if (profile?.disabled) return <div className="container page-content"><PageHeading title="Contul este dezactivat."/><Logout/></div>;
  if (!profile) return <div className="container page-content legal-page"><PageHeading title="Completează profilul." description="Rolul și grupa de vârstă determină funcțiile disponibile; drepturile administrative nu pot fi alese aici."/><Notice params={p}/><Form op="onboard" className="panel"><Field label="Rol"><select name="role"><option value="student">Elev</option><option value="parent">Părinte</option><option value="teacher">Profesor</option><option value="alumni">Absolvent</option></select></Field><Field label="Vârstă"><select name="age_band"><option value="adult">18 ani sau mai mult</option><option value="16to17">16–17 ani</option><option value="under16">Sub 16 ani</option></select></Field><input type="hidden" name="terms_version" value={legal.version}/><label className="check-field"><input type="checkbox" name="accept_terms" value="yes" required/><span>Am citit și accept <Link href="/termeni" className="text-link">termenii</Link> și am luat la cunoștință <Link href="/confidentialitate" className="text-link">informarea privind datele</Link>.</span></label><Submit>Creează profilul</Submit></Form><Logout/></div>;
  const [schools, staff] = await Promise.all([schoolOptions(), teachers()]);
  const families = data.families || [], reviews = data.reviews || [], requests = data.requests || [], checks = data.checks || [];
  const ownTeacher = data.teacher;
  return <div className="container page-content"><PageHeading title="Contul meu" description={`${label(profile.role)} · ${label(profile.age_band)} · pseudonim public: ${profile.pseudonym}`}><Logout/></PageHeading><Notice params={p}/><div className="account-layout">
    <nav className="account-nav" aria-label="Secțiunile contului"><a href="#cereri">Cereri de meditații</a><a href="#recenzii">Recenziile mele</a><a href="#verificari">Verificări</a><a href="#familie">Familie și tutelă</a>{profile.role === 'teacher' && <a href="#oferte">Ofertele mele</a>}{profile.age_band === 'adult' && <a href="#absolvent">Profil de absolvent</a>}<a href="#date">Date personale</a>{profile.staff_role && <><Link href="/admin">Administrare</Link><Link href="/admin/replies">Moderare răspunsuri</Link>{profile.staff_role==='admin'&&<Link href="/admin/privacy">Date și retenție</Link>}</>}</nav>
    <div><Section id="cereri" title="Cereri de meditații" description="Contactele apar după acceptare. Pentru copiii sub 16 ani, este necesară autorizarea tutorelui.">{requests.map(r => <article key={r.id} className="list-row"><div><h3>{r.teacher_name} · {r.subject}</h3><p className="preserve-lines">{r.message}</p><Badge tone="gray">{label(r.status)}</Badge>{r.contact && <p>Contact: <a className="text-link" href={`tel:${r.contact}`}>{r.contact}</a></p>}{r.is_teacher && r.status === 'pending' && <Decision op="requestDecide" id={r.id}/>} {!r.is_teacher && r.status === 'guardian_pending' && families.some(f => f.id === r.family_id && f.parent_id === user.id) && <Decision op="guardianDecide" id={r.id} kind="request"/>}</div></article>)}{!requests.length && <Empty title="Nu ai cereri încă."><Link href="/meditatii" className="text-link">Explorează meditațiile</Link></Empty>}</Section>
    <Section id="recenzii" title="Recenziile mele">{reviews.map(r => <article className="review" key={r.id}><Link className="text-link" href={`/profesori/${r.teacher_id}`}>{r.name}</Link><p className="preserve-lines">{r.body}</p><Badge tone="gray">{label(r.status)}</Badge>{r.reason && <p className="small">Motiv: {r.reason}</p>}{r.own ? <Link className="text-link" href={`/profesori/${r.teacher_id}#main`}>Editează printr-o nouă trimitere pentru același context și an</Link> : r.status === 'guardian_pending' && <Decision op="guardianDecide" id={r.id} kind="review"/>}</article>)}{!reviews.length && <Empty title="Nu ai trimis recenzii."/>}</Section>
    <Section id="familie" title="Familie și tutelă" description="Verificarea legăturii este distinctă de confirmarea telefonului.">{families.map(f => <div className="list-row" key={f.id}><div><h3>{f.label}</h3><Badge tone="gray">{label(f.status)}</Badge>{f.status === 'invited' && f.invited_phone === profile.phone_number && profile.role === 'parent' && <Form op="familyAccept"><input type="hidden" name="id" value={f.id}/><Submit>Acceptă invitația și solicită verificarea</Submit></Form>}{f.parent_id === user.id && f.parent_consented && <Form op="familyRevoke"><input type="hidden" name="id" value={f.id}/><Submit secondary>Retrage autorizarea</Submit></Form>}</div></div>)}{['parent', 'student'].includes(profile.role) && <details><summary>{profile.role === 'parent' ? 'Adaugă un copil în cont' : 'Invită un tutore'}</summary><Form op="family"><Field label="Nume de test / etichetă copil"><input name="label" minLength={2} maxLength={80} required/></Field><Field label="Instituția copilului"><SchoolSelect schools={schools}/></Field>{profile.role === 'student' && <Field label="Telefonul tutorelui"><input name="parent_phone" type="tel" pattern="\+[1-9][0-9]{7,14}" placeholder="+40700000002" required/></Field>}<Submit>Înregistrează legătura</Submit></Form></details>}</Section>
    <Section id="verificari" title="Verificări și revendicări" description="Încarcă exclusiv documente sintetice de test, PDF, PNG sau JPEG, maximum 5 MB. Într-un serviciu real trebuie mascate CNP-ul, adresa și datele nerelevante.">{checks.map(c => <div className="list-row" key={c.id}><div><strong>{label(c.kind)} · {c.teacher_name || c.school_name || 'Legătură de tutelă'}</strong><p>{c.academic_year} · {label(c.status)}</p>{c.reason && <p className="small">{c.reason}</p>}</div></div>)}
      <Form op="check"><div className="field-grid"><Field label="Ce verificăm?"><select name="kind" defaultValue={p.teacher && profile.role === 'teacher' ? 'claim' : 'school'}><option value="school">Apartenență școlară</option><option value="relationship">Relație cu profesorul</option>{profile.role === 'teacher' && <><option value="claim">Revendicare profil profesor</option><option value="correction">Corectare date profesionale</option></>}{profile.role === 'parent' && <option value="guardian">Tutelă</option>}</select></Field><Field label="An școlar"><input name="academic_year" defaultValue="2025–2026" pattern="20[0-9]{2}[–-]20[0-9]{2}" required/></Field></div><Field label="Instituție"><SchoolSelect schools={schools} required={false}/></Field><Field label="Profesor (pentru relație, revendicare sau corectare)"><select name="teacher_id" defaultValue={p.teacher || ownTeacher?.id || ''}><option value="">Alege profesorul</option>{staff.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Context"><select name="context"><option value="class">La clasă</option><option value="tutoring">La meditații</option></select></Field>{families.length > 0 && <Field label="Legătura de tutelă (pentru copil sau părinte)"><select name="family_id"><option value="">Nu se aplică</option>{families.map(f => <option key={f.id} value={f.id}>{f.label} · {label(f.status)}</option>)}</select></Field>} {ownTeacher && <details><summary>Date profesionale propuse (completează pentru o cerere de corectare)</summary><div className="field-grid"><Field label="Nume propus"><input name="correction_name" defaultValue={ownTeacher.name} minLength={3} maxLength={120}/></Field><Field label="Materie propusă"><input name="correction_subject" defaultValue={ownTeacher.subjects[0]} minLength={2} maxLength={80}/></Field><Field label="Instituție propusă"><SchoolSelect schools={schools} name="correction_school_id" required={false}/></Field><Field label="Anul începerii activității"><input name="correction_start_year" type="number" min={1950} max={new Date().getFullYear()} defaultValue={ownTeacher.start_year || ''}/></Field></div></details>}<Field label="Dovadă de test"><input type="file" name="document" accept="application/pdf,image/png,image/jpeg" required/></Field><Submit>Trimite pentru verificare</Submit></Form>
    </Section>
    {profile.role === 'teacher' && <Section id="oferte" title="Ofertele mele">{ownTeacher ? <><Link className="text-link" href={`/profesori/${ownTeacher.id}`}>{ownTeacher.name}</Link>{data.ownOffers?.map(o => <div className="list-row" key={o.id}><div><strong>{o.subject} · {o.level}</strong><p>{o.price} lei · {o.active ? 'Activă' : 'Inactivă'}</p>{o.active && <Form op="offerDisable"><input type="hidden" name="id" value={o.id}/><Submit secondary>Dezactivează oferta</Submit></Form>}</div></div>)}<Form op="offer"><Field label="Materie"><select name="subject">{ownTeacher.subjects.map((s: string) => <option key={s}>{s}</option>)}</select></Field><Field label="Nivel"><input name="level" defaultValue="BAC și admitere" minLength={2} maxLength={120} required/></Field><div className="field-grid"><Field label="Format"><select name="format"><option value="online">Online</option><option value="fizic">Fizic</option><option value="mixt">Mixt</option></select></Field><Field label="Localitate"><input name="city" minLength={2} maxLength={100} required defaultValue="București"/></Field><Field label="Durată (minute)"><input type="number" name="duration" min={30} max={240} defaultValue={90} required/></Field><Field label="Preț (lei)"><input type="number" name="price" min={0} max={10000} defaultValue={150} required/></Field></div><Field label="Prezentare"><textarea name="bio" defaultValue={ownTeacher.bio} minLength={20} maxLength={2000} required/></Field><label className="check-field"><input type="checkbox" name="not_current_students" value="yes" required/>Nu ofer meditații contra cost elevilor cărora le predau la clasă.</label><Submit>Publică / actualizează oferta</Submit></Form></> : <p>Revendică profilul și obține verificarea înainte de a publica oferte.</p>}</Section>}
    {profile.age_band === 'adult' && <Section id="absolvent" title="Profil de absolvent" description="Profil privat până când alegi publicarea. Datele despre carieră sunt autodeclarate."><Form op="alumni"><Field label="Nume public"><input name="public_name" defaultValue={data.alumni?.public_name || ''} minLength={2} maxLength={100} required/></Field><Field label="Liceu"><SchoolSelect schools={schools} defaultValue={data.alumni?.school_id}/></Field><Field label="Promoție"><input name="graduation" type="number" min={1950} max={new Date().getFullYear()} defaultValue={data.alumni?.graduation || 2021} required/></Field><Field label="Facultate / traseu după liceu"><input name="university" minLength={2} maxLength={150} defaultValue={data.alumni?.university || ''} required/></Field><Field label="Domeniu profesional"><input name="field" minLength={2} maxLength={100} defaultValue={data.alumni?.field || ''} required/></Field><Field label="Povestea ta"><textarea name="bio" minLength={20} maxLength={1500} defaultValue={data.alumni?.bio || ''} required/></Field><label className="check-field"><input type="checkbox" name="published" value="yes" defaultChecked={data.alumni?.published || false}/>Publică profilul. Debifează și salvează pentru retragere.</label><Submit>Salvează profilul</Submit></Form></Section>}
    <Section id="date" title="Date personale">{data.privacy?.map(r => <div className="list-row" key={r.id}><div><strong>{label(r.kind)}</strong><p>{label(r.status)}{r.reason ? ` · ${r.reason}` : ''}</p>{r.kind==='access'&&r.status==='completed'&&r.export_expires_at&&new Date(r.export_expires_at)>new Date()&&<Link className="text-link" href={`/api/privacy/${r.id}/export`}>Descarcă datele mele (export privat)</Link>}</div></div>)}<Link className="button secondary" href="/solicitari">Trimite o solicitare</Link><p className="small">Ștergerea contului și retragerea unui profil de profesor sunt cereri distincte.</p></Section></div>
  </div></div>;
}
function Decision({ op, id, kind }: { op: string; id: string; kind?: string }) {
  return <Form op={op}><input type="hidden" name="id" value={id}/>{kind && <input type="hidden" name="kind" value={kind}/>}<div className="tags"><button className="button small-button" name="decision" value="approve">Acceptă</button><button className="button secondary small-button" name="decision" value="reject">Refuză</button></div></Form>;
}
