import Link from 'next/link';
import { catalog,locations } from '@/lib/read';
import { PageHeading,SchoolCard,Empty } from '@/components/ui';
export const metadata={title:'Școli și licee'};
export default async function Schools({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  const p=await searchParams;const [{schools,count,page},places]=await Promise.all([catalog(p),locations()]);
  const counties=[...new Set(places.map(x=>x.county))];
  const pageUrl=(n:number)=>'/scoli?'+new URLSearchParams({...Object.fromEntries(Object.entries(p).filter(([,v])=>v!==undefined) as [string,string][]),page:String(n)});
  return <div className="container page-content"><PageHeading eyebrow="CATALOGUL EDUCLAR" title="O școală. Un nou început." description="Explorează instituțiile, înțelege rezultatele și compară ce contează pentru tine."/><form action="/scoli" className="filters"><label className="search-field">Școală sau localitate<input name="q" defaultValue={p.q} placeholder="Caută un nume sau un oraș…"/></label><label>Județ<select name="county" defaultValue={p.county||''}><option value="">Toate județele</option>{counties.map(c=><option key={c}>{c}</option>)}</select></label><label>Localitate<select name="city" defaultValue={p.city||''}><option value="">Toate localitățile</option>{places.filter(x=>!p.county||x.county===p.county).map(x=><option key={`${x.county}-${x.city}`}>{x.city}</option>)}</select></label><label>Tip<select name="type" defaultValue={p.type||''}><option value="">Toate tipurile</option><option value="colegiu">Colegiu</option><option value="liceu">Liceu</option><option value="gimnaziu">Gimnaziu</option></select></label><label>Date<select name="data" defaultValue={p.data||''}><option value="">Toate seturile</option><option value="official">Doar oficiale</option><option value="demo">Doar demonstrative</option></select></label><button className="button">Caută</button></form><div className="results-label"><span>{count.toLocaleString('ro-RO')} instituții găsite</span><Link href="/metodologie" className="text-link">Cum interpretăm rezultatele?</Link></div><div className="school-grid">{schools.map((s,i)=><SchoolCard key={s.id} school={s} index={i}/>)}{!schools.length&&<Empty title="Nu am găsit instituții pentru aceste filtre.">Încearcă altă localitate sau alt set de date. Catalogul oficial se completează prin importuri validate.</Empty>}</div>{count>24&&<div className="pagination">{page>1&&<Link className="button secondary" href={pageUrl(page-1)}>Înapoi</Link>}<span>Pagina {page}</span>{page*24<count&&<Link className="button secondary" href={pageUrl(page+1)}>Următoarea</Link>}</div>}</div>;
}
